print(df [['Crédit', 'Débit','Taux']].dtypes)
avg_buy_rate = df[df['Débit']>0]['Taux'].mean()
avg_sell_rate = df[df ['Crédit']>0]['Taux'].mean()
print("\nAperçu des données :")
print(df[['Crédit', 'Débit','Taux']].head())
print("\n columns name in your excel file:")
print("\ntotal profit :", total_profit)
print("\n average buy :", avg_buy_rate)
print("\n average sell :", avg_sell_rate)
print(df.columns) 
